# Generated by Django 4.2.3 on 2023-11-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='headshot',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedIn',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
