# Generated by Django 4.2.3 on 2023-11-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0002_alter_car_image_alter_member_headshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(upload_to='uploads/cars/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='headshot',
            field=models.FileField(upload_to='uploads/members/'),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='image',
            field=models.FileField(upload_to='uploads/merchItems/'),
        ),
    ]
