# Generated by Django 4.2.3 on 2023-11-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0005_alter_adminmember_headshot_alter_car_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmember',
            old_name='name',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='adminmember',
            old_name='email',
            new_name='school_email',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='car_name',
        ),
        migrations.RenameField(
            model_name='techincalmember',
            old_name='name',
            new_name='member_name',
        ),
        migrations.RenameField(
            model_name='techincalmember',
            old_name='email',
            new_name='school_email',
        ),
    ]
