# Generated by Django 4.2.3 on 2023-11-03 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0006_rename_name_adminmember_member_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmember',
            name='headshot',
            field=models.FileField(help_text='Upload a headshot image of the member.', upload_to='adminMembers/'),
        ),
        migrations.AlterField(
            model_name='adminmember',
            name='linkedIn',
            field=models.URLField(help_text="Enter the member's LinkedIn profile URL."),
        ),
        migrations.AlterField(
            model_name='adminmember',
            name='member_name',
            field=models.CharField(help_text="Enter the member's name.", max_length=200),
        ),
        migrations.AlterField(
            model_name='adminmember',
            name='school_email',
            field=models.EmailField(help_text="Enter the member's school email address.", max_length=200),
        ),
        migrations.AlterField(
            model_name='adminmember',
            name='title',
            field=models.CharField(help_text="Enter the member's title.", max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(help_text='Enter the name of the car.', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='chassis',
            field=models.CharField(help_text='Enter the chassis details of the car.', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='competition_placement',
            field=models.CharField(help_text="Enter the car's competition placement.", max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(help_text='Upload an image of the car.', upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_achievement',
            field=models.CharField(help_text="Enter the car's main achievement.", max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_unit',
            field=models.CharField(help_text='Enter the power unit details of the car.', max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.CharField(help_text='Enter the weight of the car.', max_length=200),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='image',
            field=models.FileField(help_text='Upload the image of the merch item.', upload_to='merchItems/'),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='item_name',
            field=models.CharField(help_text="Enter the item's name.", max_length=200),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text="Enter the item's price.", max_digits=6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(9999.99)]),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='size',
            field=models.BooleanField(help_text='Check if a size section should be included.'),
        ),
        migrations.AlterField(
            model_name='techincalmember',
            name='linkedIn',
            field=models.URLField(help_text="Enter the member's LinkedIn profile URL."),
        ),
        migrations.AlterField(
            model_name='techincalmember',
            name='member_name',
            field=models.CharField(help_text="Enter the member's name.", max_length=200),
        ),
        migrations.AlterField(
            model_name='techincalmember',
            name='school_email',
            field=models.EmailField(help_text="Enter the member's school email address.", max_length=200),
        ),
        migrations.AlterField(
            model_name='techincalmember',
            name='title',
            field=models.CharField(help_text="Enter the member's title.", max_length=200),
        ),
    ]
