# Generated by Django 4.2.3 on 2023-11-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0007_alter_adminmember_headshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmember',
            name='linkedIn',
            field=models.URLField(blank=True, help_text="Enter the member's LinkedIn profile URL.", null=True),
        ),
        migrations.AlterField(
            model_name='techincalmember',
            name='linkedIn',
            field=models.URLField(blank=True, help_text="Enter the member's LinkedIn profile URL.", null=True),
        ),
    ]
