# Generated by Django 4.2.3 on 2023-11-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0008_alter_adminmember_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmember',
            name='headshot',
            field=models.FileField(help_text='Upload a headshot image of the member in a 1x1 format.', upload_to='adminMembers/'),
        ),
        migrations.AlterField(
            model_name='techincalmember',
            name='headshot',
            field=models.FileField(help_text='Upload a headshot image of the member in a 1x1 format.', upload_to='technicalMembers/'),
        ),
    ]
