# Generated by Django 4.2.3 on 2023-11-03 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0010_alter_adminmember_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='competition_placement',
            field=models.CharField(help_text="Enter the car's competition placement. Format: placement/# of teams. Ex: 50/120.", max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_achievement',
            field=models.TextField(help_text="Enter the car's main achievement.", max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.IntegerField(help_text='Enter the weight of the car.', validators=[django.core.validators.MaxValueValidator(limit_value=999, message='Weight must have at most 3 digits.')]),
        ),
    ]
