# Generated by Django 4.2.3 on 2023-11-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0011_alter_car_competition_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_name',
            field=models.CharField(help_text='Enter the name of the car in the format: RRR-YYYY. Ex: RRR-2023.', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='chassis',
            field=models.CharField(blank=True, help_text='Enter the chassis details of the car. (Optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='competition_placement',
            field=models.CharField(blank=True, help_text="Enter the car's competition placement. Format: placement/# of teams. Ex: 50/120. (Optional)", max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='main_achievement',
            field=models.TextField(blank=True, help_text="Enter the car's main achievement. (Optional)", max_length=200),
        ),
        migrations.AlterField(
            model_name='car',
            name='power_unit',
            field=models.CharField(blank=True, help_text='Enter the power unit details of the car. (Optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Enter the weight of the car. (Optional)', null=True),
        ),
    ]
