# Generated by Django 4.2.3 on 2023-11-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0012_alter_car_car_name_alter_car_chassis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchitem',
            name='item_name',
            field=models.CharField(help_text="Enter the item's name. Do not include an underscore ('_') in the name.", max_length=200),
        ),
    ]
