# Generated by Django 4.2.1 on 2023-11-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0014_rename_adminmember_adminteammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchitem',
            name='image',
            field=models.FileField(help_text='Upload the image of the merch item. Preferably a .png file with no background.', upload_to='merchItems/'),
        ),
    ]
