# Generated by Django 4.2.3 on 2023-11-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0019_alter_carshowlocation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshowlocation',
            name='date',
            field=models.DateField(blank=True, default=None, help_text='Enter the date the car show will take place.', null=True),
        ),
        migrations.AddField(
            model_name='carshowlocation',
            name='end_time',
            field=models.TimeField(blank=True, default=None, help_text='Enter the time the car show will end.', null=True),
        ),
        migrations.AddField(
            model_name='carshowlocation',
            name='start_time',
            field=models.TimeField(blank=True, default=None, help_text='Enter the time the car show will start.', null=True),
        ),
    ]
