# Generated by Django 4.2.3 on 2023-11-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0020_carshowlocation_date_carshowlocation_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshowlocation',
            name='end_time',
            field=models.CharField(blank=True, default=None, help_text='Enter the time the car show will end. Format: TT:TT PM. Ex: 9:00 PM', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='carshowlocation',
            name='start_time',
            field=models.CharField(blank=True, default=None, help_text='Enter the time the car show will start. Format: TT:TT AM. Ex: 9:00 AM', max_length=8, null=True),
        ),
    ]
