# Generated by Django 4.2.3 on 2023-11-04 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0021_alter_carshowlocation_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='Enter the frequently asked question.', max_length=200)),
                ('answer', models.TextField(help_text='Enter the answer to the FAQ.', max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='carshowlocation',
            name='location',
            field=models.TextField(help_text='Enter the location of the car show in the format of an embedded HTML Google Map location. Tutorial on how to do this: <a href="https://support.google.com/maps/answer/144361?hl=en&co=GENIE.Platform%3DDesktop" target="_blank">Google Map</a>.', max_length=2000),
        ),
    ]
