# Generated by Django 4.2.3 on 2023-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0022_faqquestion_alter_carshowlocation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchitem',
            name='secondary_image',
            field=models.FileField(blank=True, help_text='Upload the secondary image of the merch item. This could be the back of the shirt. Preferably a .png file with no background. (Optional)', null=True, upload_to='merchItems/'),
        ),
        migrations.AlterField(
            model_name='adminteammember',
            name='school_email',
            field=models.EmailField(help_text="Enter the member's school email address. Ex: raiderred@ttu.edu.", max_length=200),
        ),
        migrations.AlterField(
            model_name='carshowlocation',
            name='end_time',
            field=models.CharField(blank=True, default=None, help_text='Enter the time the car show will end. Format: TT:TT PM. Ex: 9:00 PM.', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='carshowlocation',
            name='start_time',
            field=models.CharField(blank=True, default=None, help_text='Enter the time the car show will start. Format: TT:TT AM. Ex: 9:00 AM.', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='size',
            field=models.BooleanField(help_text='Toggle on if a size section should be included. Ex: Shirts.'),
        ),
        migrations.AlterField(
            model_name='techincalteammember',
            name='school_email',
            field=models.EmailField(help_text="Enter the member's school email address. Ex: raiderred@ttu.edu.", max_length=200),
        ),
    ]
