# Generated by Django 4.2.3 on 2023-11-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0023_merchitem_secondary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminteammember',
            name='headshot',
            field=models.ImageField(help_text='Upload a headshot image of the member in a 1x1 format.', upload_to='adminMembers/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(help_text='Upload an image of the car.', upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='image',
            field=models.ImageField(help_text='Upload the image of the merch item. Preferably a .png file with no background.', upload_to='merchItems/'),
        ),
        migrations.AlterField(
            model_name='merchitem',
            name='secondary_image',
            field=models.ImageField(blank=True, help_text='Upload the secondary image of the merch item. This could be the back of the shirt. Preferably a .png file with no background. (Optional)', null=True, upload_to='merchItems/'),
        ),
        migrations.AlterField(
            model_name='techincalteammember',
            name='headshot',
            field=models.ImageField(help_text='Upload a headshot image of the member in a 1x1 format.', upload_to='technicalMembers/'),
        ),
    ]
