# Generated by Django 4.2.3 on 2023-11-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0024_alter_adminteammember_headshot_alter_car_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarShowLocation',
            new_name='CarShow',
        ),
    ]
