# Generated by Django 4.2.3 on 2023-11-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0026_carshow_email_preregister_payment_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carshow',
            name='email_subject',
        ),
    ]
