# Generated by Django 4.2.3 on 2023-11-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0027_remove_carshow_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshow',
            name='date',
            field=models.DateField(default=None, help_text='Enter the date the car show will take place.'),
        ),
        migrations.AlterField(
            model_name='carshow',
            name='end_time',
            field=models.CharField(blank=True, default=None, help_text='Enter the time the car show will end. Format: TT:TT PM. Ex: 9:00 PM. (Optional)', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='carshow',
            name='start_time',
            field=models.CharField(blank=True, default=None, help_text='Enter the time the car show will start. Format: TT:TT AM. Ex: 9:00 AM. (Optional)', max_length=8, null=True),
        ),
    ]
