# Generated by Django 4.2.3 on 2023-11-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0028_alter_carshow_date_alter_carshow_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carshow',
            old_name='location',
            new_name='location_HTML',
        ),
        migrations.AddField(
            model_name='carshow',
            name='location_name',
            field=models.CharField(default='Unknown', help_text='Enter the name of the location. This will be used when sending emails to people who register. Ex: Commuter North Parking Lot.', max_length=200),
        ),
    ]
