# Generated by Django 4.2.3 on 2023-11-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0029_rename_location_carshow_location_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carshow',
            name='location_name',
        ),
    ]
