# Generated by Django 4.2.3 on 2023-11-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0030_remove_carshow_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshow',
            name='location_name',
            field=models.CharField(default='Unknown', help_text='Enter the name of the location. This will be used when sending emails to people who register. Ex: Commuter North Parking Lot.', max_length=200),
        ),
    ]
