# Generated by Django 4.2.3 on 2023-11-09 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0033_alter_carshowattendee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshow',
            name='preregister_cost',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Enter the cost of registering a car early.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AddField(
            model_name='carshow',
            name='register_cost',
            field=models.DecimalField(decimal_places=2, default=None, help_text='Enter the cost of registering a car at the entrance.', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999.99)]),
        ),
        migrations.AlterField(
            model_name='adminteammember',
            name='linkedIn',
            field=models.URLField(blank=True, help_text="Enter the member's LinkedIn profile URL. (Optional)", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='techincalteammember',
            name='linkedIn',
            field=models.URLField(blank=True, help_text="Enter the member's LinkedIn profile URL. (Optional)", max_length=500, null=True),
        ),
    ]
