# Generated by Django 4.2.3 on 2023-11-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0034_carshow_preregister_cost_carshow_register_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(help_text="Enter the sponsor's name.", max_length=200)),
                ('sponsor_logo', models.ImageField(help_text='Upload an image of the sponsors logo. Make sure the background is either transparent or white. ', upload_to='sponsors/')),
                ('sponsor_link', models.URLField(blank=True, help_text="Enter the URL to the sponsor's website. This is so that people can easily click on the image and go straight to the sponsor's page. (Optional only if they do not have one)", max_length=500, null=True)),
            ],
        ),
    ]
