# Generated by Django 4.2.7 on 2024-01-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0038_alter_adminteammember_headshot_alter_car_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminteammember',
            name='first',
            field=models.BooleanField(blank=True, default=False, help_text='Toggle on if the member should be first. Ex: President. This is used for ordering the team page.', null=True),
        ),
        migrations.AddField(
            model_name='adminteammember',
            name='sub_section',
            field=models.CharField(blank=True, help_text="Enter the member's sub_section. Ex. Aero, Powertrain, Electrical, etc. This is used for ordering the team page.", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='techincalteammember',
            name='first',
            field=models.BooleanField(blank=True, default=False, help_text='Toggle on if the member should be first. Ex: President. This is used for ordering the team page.', null=True),
        ),
        migrations.AddField(
            model_name='techincalteammember',
            name='sub_section',
            field=models.CharField(blank=True, help_text="Enter the member's sub_section. Ex. Aero, Powertrain, Electrical, etc. This is used for ordering the team page.", max_length=200, null=True),
        ),
    ]
