# Generated by Django 4.2.7 on 2024-01-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0039_adminteammember_first_adminteammember_sub_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqquestion',
            name='first',
            field=models.BooleanField(blank=True, default=False, help_text='Toggle on if the question should be first after how to join. Ex: General body meetings. This is used for ordering the FAQ page.', null=True),
        ),
    ]
