# Generated by Django 4.2.7 on 2024-01-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0040_faqquestion_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminteammember',
            name='first',
            field=models.BooleanField(default=False, help_text='Toggle on if the member should be first. Ex: President. This is used for ordering the team page.'),
        ),
        migrations.AlterField(
            model_name='adminteammember',
            name='sub_section',
            field=models.CharField(default=None, help_text="Enter the member's sub_section. Ex. Aero, Powertrain, Electrical, etc. This is used for ordering the team page.", max_length=200),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='first',
            field=models.BooleanField(default=False, help_text='Toggle on if the question should be first after how to join. Ex: General body meetings. This is used for ordering the FAQ page.'),
        ),
        migrations.AlterField(
            model_name='techincalteammember',
            name='first',
            field=models.BooleanField(default=False, help_text='Toggle on if the member should be first. Ex: President. This is used for ordering the team page.'),
        ),
        migrations.AlterField(
            model_name='techincalteammember',
            name='sub_section',
            field=models.CharField(default=None, help_text="Enter the member's sub_section. Ex. Aero, Powertrain, Electrical, etc. This is used for ordering the team page.", max_length=200),
        ),
    ]
