# Generated by Django 4.2.7 on 2024-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRRApp', '0041_alter_adminteammember_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshow',
            name='show_registration',
            field=models.BooleanField(blank=True, default=True, help_text="Toggle off if you want to hide the registration. Ex: After the car show you won't want people still registering.", null=True),
        ),
    ]
