name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.x]

    steps:
    - name: Clear Python version cache
      run: |
        echo "::remove-matcher owner=python-version::"

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up environment variables
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
        echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> $GITHUB_ENV
        echo "SHEETS_USERNAME=${{ secrets.SHEETS_USERNAME }}" >> $GITHUB_ENV
        echo "SHEETS_PASSWORD=${{ secrets.SHEETS_PASSWORD }}" >> $GITHUB_ENV

    - name: Run Tests
      run: |
        python manage.py test